name: Deploy Django Application

on:
  # push:
  #   branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

    - name: Extract commit hash
      id: vars
      run: echo "commit=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # The key issue is here - We need to properly scan the host
    - name: Setup SSH known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_HOST }} $(ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} 2>/dev/null)" >> ~/.ssh/known_hosts

    - name: Deploy to server (Skipped - Local VM not accessible)
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        COMMIT_HASH: ${{ steps.vars.outputs.commit }}
      run: |
        echo "Note: Deployment to local VM with IP $SSH_HOST is skipped."
        echo "GitHub Actions cannot reach your local Multipass VM with a private IP."
        echo "Please see the deployment instructions for alternatives."
        
        # Simulating successful deployment for demo purposes
        echo "✓ Build successful"
        echo "✓ Tests passed"
        echo "✓ Deployment package ready"
        echo "⚠ Actual deployment skipped - VM not accessible from GitHub Actions"
        
        # The deployment steps would have been:
        echo "If deployment was possible, these steps would be executed:"
        echo "1. Install requirements"
        echo "2. Run migrations"
        echo "3. Collect static files"
        echo "4. Restart application"
        echo "5. Deploy commit: $COMMIT_HASH"
