name : Build and Deploy Django 

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight UTC


jobs:
  build_and_test:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: echo "Linting is skipped for this run."

    - name: Run tests
      run : python manage.py test



  deploy:
    needs: [build_and_test]
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # uses: actions/checkout@v3
      run: echo "Code checkout is skipped for this run."

    - name: Extract commit hash
      id: vars
      run: echo "Commit hash extraction is skipped for this run."

    - name: Set up SSH
      run: echo "SSH setup is skipped for this run."

    - name: Deploy to server
      run: echo "Deployment is skipped for this run."